apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    environment: dev
    project: expense
    modue: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: expense
      modue: frontend
  template:
    metadata:
      name: frontend
      labels:
        environment: dev
        project: expense
        modue: frontend
    spec:
      containers:
      - name: frontend
        image: amarnadh31/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense

spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: expense
    modue: frontend
  ports:
  - name: frontend-service
    protocol: TCP
    port: 80
    targetPort: 80