apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    environment: dev
    project: expense
    modue: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: expense
      modue: backend
  template:
    metadata:
      name: backend
      labels:
        environment: dev
        project: expense
        modue: backend
    spec:
      initContainers:
      - name: mysql-check
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: amarnadh31/backend:v2
        envFrom:
        - configMapRef:
            name: backend-config
        readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    environment: dev
    project: expense
    modue: backend
  ports:
  - name: backend-service
    protocol: TCP
    port: 8080
    targetPort: 8080