apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    environment: dev
    project: expense
    modue: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      project: expense
      modue: backend
  template:
    metadata:
      name: backend
    spec:
      containers:
      - name: backend
        image: amarnadh31/backend:v2
        envFrom:
        - configMapRef:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    environment: dev
    project: expense
    modue: backend
  ports:
  - name: backend-service
    protocol: TCP
    port: 8080
    targetPort: 8080