apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    environment: dev
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      module: mysql
      environment: dev
      project: expense
  template:
    metadata:
      name: db
      labels:
        module: mysql
        environment: dev
        project: expense
    spec:
      containers:
        - name: mysql
          image: amarnadh31/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    module: mysql
    environment: dev
    project: expense
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
